apiVersion: v1
kind: Service
metadata:
  name: pingpong-server-service
spec:
  selector:
    app: pingpong-server # This must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80       # The port the service will be exposed on externally
      targetPort: 8080 # The port your container (pingpong-server) is listening on
  type: LoadBalancer # Use NodePort for local clusters if LoadBalancer isn't availablea