apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-server
  template:
    metadata:
      labels:
        app: pingpong-server
    spec:
      serviceAccountName: default # Replace if using custom K8s service account for Workload Identity
      containers:
        - name: pingpong-server-container
          image: tuanbieber/pingpong-server:v1.1.37
          env:
            - name: DB_USER
              value: "729560812361-compute"
            - name: DB_PASS
              value: ""
            - name: DB_NAME
              value: "saigoncoder"
            - name: INSTANCE_CONNECTION_NAME
              value: "imposing-water-423814-u0:asia-southeast1:saigoncoder-mysql-8"
            - name: PRIVATE_IP
              value: "10.19.0.3"
          resources:
            requests:
              cpu: "30m"
              memory: "50Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          securityContext:
            runAsNonRoot: true
          args:
            - "--port=3306"
            - "imposing-water-423814-u0:asia-southeast1:saigoncoder-mysql-8"
            - "--auto-iam-authn"
          resources:
            requests:
              cpu: "30m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
