apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: empi
  name: pod-reader-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["list", "get", "watch"]