apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: empi
subjects:
- kind: User
  name: "tuan1604lts@gmail.com" # The user from the error message
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader-role # The name of the Role created above
  apiGroup: rbac.authorization.k8s.io